name: pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  deploy-dir: public

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build karax app
        run: nimble -y build -d:danger

      - name: Build index page
        run: nimble render

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
